import { motion } from 'framer-motion';
import type { CSSProperties, ReactNode } from 'react';

type ImageProps = {
    src: string;
    alt: string;
    className?: string;
    style?: CSSProperties;
    width?: number;
    height?: number;
};

/**
 * Pre-rendered device mockups generated by scripts/mockups/generate.py.
 * The drop shadow is baked into the WebP, so we just render an <img>.
 */
export function MockupImage({ src, alt, className = '', style, width, height }: ImageProps) {
    return (
        <img
            src={src}
            alt={alt}
            width={width}
            height={height}
            loading="lazy"
            decoding="async"
            draggable={false}
            className={`max-w-full h-auto select-none ${className}`}
            style={style}
        />
    );
}

type FloatProps = {
    children: ReactNode;
    className?: string;
    style?: CSSProperties;
    delay?: number;
};

export function FloatingDevice({ children, className = '', style, delay = 0 }: FloatProps) {
    return (
        <motion.div
            initial={{ opacity: 0, y: 32 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: '-80px' }}
            transition={{ duration: 0.9, delay, ease: [0.16, 1, 0.3, 1] }}
            className={className}
            style={style}
        >
            {children}
        </motion.div>
    );
}
